version: 2.1

orbs:
  lein: replikativ/clj-lein@0

workflows:
  build-test-and-deploy:
    jobs:
      - lein/setup
      - lein/format:
          requires:
            - lein/setup
      - lein/unittest:
          requires:
            - lein/setup
      - lein/build:
          requires:
            - lein/setup
      - lein/deploy-snapshot:
          context: clojars-deploy
          filters:
            branches:
              only: development
          requires:
            - lein/setup
            - lein/format
            - lein/build
            - lein/unittest
      - lein/deploy-release:
          context: clojars-deploy
          filters:
            branches:
              only: master
          requires:
            - lein/setup
            - lein/format
            - lein/build
            - lein/unittest
